apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-1
spec:
  containers:
  - name: demo-container-1
    image: nginx
    env:
    - name: Username
      valueFrom:   
        secretKeyRef:   
          name: my-secret
          key: username