apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-3
spec:
  containers:
  - name: demo-container-3
    image: nginx
    env:
    - name: MY-NAME
      valueFrom:   
        configMapKeyRef:   
          name: configmap-2
          key: fname
