apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-5
spec:
  containers:
  - name: demo-container-5
    image: nginx
    volumeMounts:
      - name: config
        mountPath: /etc/config
  volumes:
  - name: config
    configMap:
      name: configmap-3
